### ISSUE TITLE
Bad font size breaks `ptable_heatmap`

### ISSUE THREAD

**Issue by CompRhys** [janosh/pymatviz#188] opened 2024-07-30 17:25 UTC
![image](https://github.com/user-attachments/assets/695ae124-a7eb-4c97-9ede-cffc4557b78f)

Recent changes appear to have broken the matplotlib heatmaps. @DanielYang59

**Comment by DanielYang59** [comment] 2024-07-31 02:14
Thanks for reporting, and sorry for the trouble. Looks like bad font size to me, can you provide the code to reproduce that plot?

**Comment by CompRhys** [comment] 2024-08-21 20:38
Sorry for the slow reply, if you check out this branch (https://github.com/janosh/matbench-discovery/pull/125) and run the `eda_wbm.py` file you will also see similar graphical issues. This is a different example to the one above but shows it does crop up commonly

**Comment by DanielYang59** [comment] 2024-08-22 03:12
No problem I would look into this ASAP

**Comment by DanielYang59** [comment] 2024-08-22 05:21
I'm able to reproduce similar issues with the following code extracted from the `eda_wbm.py` (should be bad font size/total number of digits, would try to fix this ASAP):
```python
import pandas as pd
import pymatviz as pmv
from matplotlib.colors import SymLogNorm
from pymatviz.enums import Key

from matbench_discovery import PDF_FIGS, ROOT
from matbench_discovery import plots as plots
from matbench_discovery.data import DataFiles, df_wbm


DATA_PAGE = f"{ROOT}/site/src/routes/data"


# Load MP training set
df_mp = pd.read_csv(DataFiles.mp_energies.path, na_filter=False, na_values=[])
df_mp = df_mp.rename(columns={"formula_pretty": Key.formula})
df_mp.loc[
    df_mp[Key.mat_id].isin(["mp-1080032", "mp-1179882", "mp-1009221"]), Key.formula
] = "NaN"
df_mp[df_mp[Key.formula].isna() | (df_mp[Key.formula] == "")]

wbm_occu_counts = pmv.count_elements(df_wbm[Key.formula], count_mode="occurrence")
wbm_comp_counts = pmv.count_elements(df_wbm[Key.formula], count_mode="composition")
mp_occu_counts = pmv.count_elements(df_mp[Key.formula], count_mode="occurrence")
mp_comp_counts = pmv.count_elements(df_mp[Key.formula], count_mode="composition")

all_counts = (
    ("wbm", "occurrence", wbm_occu_counts),
    ("wbm", "composition", wbm_comp_counts),
    ("mp", "occurrence", mp_occu_counts),
    ("mp", "composition", mp_comp_counts),
)


for dataset, count_mode, elem_counts in all_counts:
    filename = f"{dataset}-element-counts-by-{count_mode}"
    elem_counts.to_json(f"{DATA_PAGE}/{filename}.json")

    ax_mp_cnt = pmv.ptable_heatmap(
        elem_counts,
        value_fmt=lambda x, _: pmv.utils.si_fmt(x, ".0f"),
        cbar_label_fmt=lambda x, _: pmv.utils.si_fmt(x, ".0f"),
        cbar_title=f"{dataset.upper()} Element Count",
        log=(log := SymLogNorm(linthresh=100)),
        return_type="figure",
    )
    if log:
        filename += "-symlog" if isinstance(log, SymLogNorm) else "-log"
    pmv.save_fig(ax_mp_cnt, f"{PDF_FIGS}/{filename}.pdf")
```

**Comment by DanielYang59** [comment] 2024-09-06 03:03
Closing as I believe it is resolved by https://github.com/janosh/matbench-discovery/pull/125#issuecomment-2333118569, free feel to comment if it's not the case.

**Comment by DanielYang59** [comment] 2024-09-06 12:59
>  if those custom kwargs fix the issue, we should make those values the new defaults.

I would reply in that PR :)

**Comment by DanielYang59** [comment] 2024-09-10 02:36
I believe this could be closed https://github.com/janosh/matbench-discovery/pull/125#issuecomment-2338235109

**Closed by DanielYang59** 2024-09-10 02:36 UTC
Labels: bug, matplotlib, ptable

**Comment by DanielYang59** [comment] 2024-09-10 12:56
>  whenever there are too many digits to fit in the element tile, the tile shrinks

Yep I noticed this issue too (not just heat value, but any overly large font). 

The way tile size is handled is a bit complicated and confusing, looks like when the font is overly large, the tile shrinks (like taking the `max(figure_size, font_size)`).
